"""Revision ID: 46b5d63ed3b2
Revises: 2378db04079a
Create Date: 2025-09-02 14:21:32.542289

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "46b5d63ed3b2"
down_revision: str | None = "2378db04079a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
