version: "3.8"

services:
  aiexec:
    image: aiexecai/aiexec:1.0-alpha
    ports:
      - "7860:7860"
    depends_on:
      - postgres
    environment:
      - AIEXEC_DATABASE_URL=postgresql://aiexec:aiexec@postgres:5432/aiexec
      # This variable defines where the logs, file storage, monitor data and secret keys are stored.
      - AIEXEC_CONFIG_DIR=app/aiexec
    volumes:
      - aiexec-data:/app/aiexec

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: aiexec
      POSTGRES_PASSWORD: aiexec
      POSTGRES_DB: aiexec
    ports:
      - "5432:5432"
    volumes:
      - aiexec-postgres:/var/lib/postgresql/data

volumes:
  aiexec-postgres:
  aiexec-data:
