name: Security Scan

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    # Weekly security scan
    - cron: '0 0 * * 0'

jobs:
  bandit-scan:
    name: Run Bandit Security Scan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Bandit
      run: |
        python -m pip install --upgrade pip
        pip install bandit

    - name: Run Bandit security scan
      run: |
        bandit -r . -c pyproject.toml -f json -o bandit-results.json
      continue-on-error: true  # Don't fail the build, we'll handle it in the next step

    - name: Upload Bandit results
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: bandit-results.json

  dependency-check:
    name: Dependency Security Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Safety
      run: |
        python -m pip install --upgrade pip
        pip install safety

    - name: Run Safety check
      run: |
        safety check --full-report --output json > safety-report.json
      continue-on-error: true

    - name: Upload Safety results
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: safety-report.json

  # Add more security scanning tools as needed
  # e.g., TruffleHog for secrets scanning, etc.
