name: Template Tests

on:
  pull_request:
    paths:
      - 'api/base/aiexec/initial_setup/starter_projects/**'
      - 'api/tests/unit/template/test_starter_projects.py'
      - 'api/base/aiexec/utils/template_validation.py'
      - '.github/workflows/template-tests.yml'
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  test-starter-projects:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "latest"

    - name: Install dependencies
      run: |
        uv sync --dev

    - name: Test all starter project templates
      run: |
        uv run pytest api/tests/unit/template/test_starter_projects.py -v -n auto